//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipmentManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentInfo
    {
        public string ShipmentID { get; set; }
        public string ImportDate { get; set; }
        public string ImportTime { get; set; }
        public string ImportLocation { get; set; }
        public string ExportDate { get; set; }
        public string ExportTime { get; set; }
        public string ExportLocation { get; set; }
    }
}
